name: Github packages publish

on: workflow_dispatch

jobs:
  publish:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        platforms: [ ubuntu-22.04, windows-latest, macos-13, macos-14 ]

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js 18.x
      uses: actions/setup-node@v6
      with:
        node-version: 18.x
    - uses: actions/setup-python@v6
      with:
        python-version: 3.11
    - run: npm install --ignore-scripts
    - run: npx @mapbox/node-pre-gyp configure
    - run: npx @mapbox/node-pre-gyp build -j max
    - run: npm test
      env:
        MOCHA_TEST_CONCURRENCY: 0
    - run: npx @mapbox/node-pre-gyp package
    - run: npx @mmomtchev/node-pre-gyp-github publish
      env:
        NODE_PRE_GYP_GITHUB_TOKEN: ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
