name: Test release

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      testConcurrency:
        description: 'Check that parallel tests run in parallel (requires real CPUs)'
        required: false
        default: 0


jobs:
  test_published:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        platforms: [ ubuntu-18.04, ubuntu-20.04, windows-2019, macos-11 ]
        node-version: [ 14.x, 16.x, 18.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g npm@latest
    - run: npm install --ignore-scripts
    - run: npx @mapbox/node-pre-gyp install
    - name: Run unit tests
      run: npm test
      env:
        MOCHA_TEST_CONCURRENCY: ${{ github.event.inputs.testConcurrency }}
