name: Test release

on:
  release:
    types: [published]

  workflow_dispatch:
    inputs:
      testConcurrency:
        description: 'Check that parallel tests run in parallel (requires real CPUs)'
        required: false
        default: '0'


jobs:
  test_published:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        platforms: [ ubuntu-22.04, windows-latest, macos-13, macos-14 ]
        node-version: [ 18.x, 20.x, 22.x ]

    steps:
    - uses: actions/checkout@v5
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v6
      with:
        node-version: ${{ matrix.node-version }}
    - uses: actions/setup-python@v6
      with:
        python-version: 3.11
    - run: npm install --ignore-scripts
    - run: npx @mapbox/node-pre-gyp install
    - name: Run unit tests
      run: npm test
      env:
        MOCHA_TEST_CONCURRENCY: ${{ github.event.inputs.testConcurrency }}
