# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      testConcurrency:
        description: 'Check that parallel tests run in parallel (requires real CPUs)'
        required: false
        default: 0


jobs:
  test:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        node-version: [ 12.x, 14.x, 16.x, 17.x ]
        platforms: [ ubuntu-20.04, macos-10.15, windows-2019 ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npx node-pre-gyp configure
    - name: Build from sources
      run: npx node-pre-gyp build -j max
    - name: Run unit tests
      run: npm test
      env:
        MOCHA_TEST_CONCURRENCY: ${{ github.event.inputs.testConcurrency }}


  codecov:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install --ignore-scripts
    - run: npx node-pre-gyp configure --debug --enable_coverage
    - name: Build from sources
      run: npx node-pre-gyp build -j max
    - name: Run unit tests
      run: npm test
      env:
        MOCHA_TEST_CONCURRENCY: 0
    - name: Collect coverage data
      run: npm run gcov
    - name: Send data to codecov
      run: npm run codecov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
