name: Test published packages

on:
  release:
    types: [published]

  workflow_dispatch:


jobs:
  test_published:

    runs-on: ${{ matrix.platforms }}

    strategy:
      matrix:
        platforms: [ ubuntu-18.04, ubuntu-20.04, windows-2019, macos-10.15 ]
        node-version: [ 12.x, 14.x, 16.x, 17.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install --ignore-scripts
    - run: npx @mapbox/node-pre-gyp install
    - run: npm test
